### ISSUE TITLE
doco: no "replay" cache size control, "custo" typo

### ISSUE THREAD

**Issue by apjanke** [gnachman/iterm2-website#15]
In the iTerm2 documentation [Highlights for New Users page](http://iterm2.com/documentation-highlights.html), it talks about a control for the instant replay buffer size.

> Instant replay mode:
By default, each session uses up to 4MB to save its instant replay history, and this can be adjusted under Preferences > General > Instant Replay uses __ MB per session.

But I don't see that control in the preferences on 2.1. Is this something from a newer beta version? Should it be noted as such, or is there separate doco for the 2.9 beta series?

#### "custo"  ####

Also, in the [Preferences section](http://iterm2.com/documentation-preferences.html), "custom" is misspelled as "custo", under "Pointer".

**Comment by gnachman** [comment]
Yes, it should be there in 2.1. See here:

![ir](https://cloud.githubusercontent.com/assets/427546/9513631/ff53e55c-4c46-11e5-919c-c701ee895a35.png)

**Comment by gnachman** [comment]
I'll fix the typo in the next push of the website. Thanks for pointing that out. The setting is there in 2.1, see here:

![ir](https://cloud.githubusercontent.com/assets/427546/9513683/6ea5164c-4c47-11e5-868a-620afd3c5451.png)

**Comment by apjanke** [comment]
I must have been blind or very tired. The setting's right there, all right. Sorry about that.
