### ISSUE TITLE
Shell integration broken by December 2015 changes to bash_startup.in

### ISSUE THREAD

**Issue by nkurz** [gnachman/iterm2-website#21]
Hello --

I had shell integration working with an existing remote host, but was unable to get it to work when I tried installing the integration features on a new host.   As part of trying to understand this, I upgraded .iterm2_shell_integration.bash to the current Dec 5 2015 version on the previously working host, and found that it stopped working!

Reverting to the Nov 15 2015 version of bash_startup.in (https://github.com/gnachman/iterm2-website/blob/ab9896bfea4d88d9ad407997d1d1904bae4c3f73/source/misc/bash_startup.in) got it working again for me.  Installing that version also got the new host to work.   So I think there must be something wrong with current version.  

The main visible symptom of the non-working version is the lack of the blue triangle marks on the left of the prompt.  Upload and download with 'scp' work, but only from the top directory (the current directory is not updated properly).  No error messages observed.   The remote systems are both Ubuntu 14.04.3 LTS running GNU bash, version 4.3.11(1)-release. 

I can provide more information and debugging if desired.  Thanks for providing such wonderful software!

ps.  I noticed another user reported what might be the same issue here https://gitlab.com/gnachman/iterm2/issues/4133.

**Comment by dsedivec** [comment]
I think [my report on the iTerm2 mailing list](https://groups.google.com/d/msg/iterm2-discuss/euJYAAKOSJc/BrzAc2uSCAAJ) may be similar/same issue.

**Comment by gnachman** [comment]
The commit you're referring to unintentionally commited a change to the bash shell integration script. I've reverted it. If you reinstall, it should start working. Sorry for the inconvenience.
