### ISSUE TITLE
Can you create the "improvedHostnameDetection" branch?

### ISSUE THREAD

**Issue by robertpeteuil** [gnachman/iterm2-website#23]
I'm ready to create a pull request for my updates, but I'd like to send it to the "improvedHostnameDetection" branch as we discussed (instead of master). 

Unfortunately Github only allows you to specify existing branches in Pull Requests, so I need you to manually create that branch before I can create the request.

Thanks and let me know if you have any questions,
Robert

**Comment by gnachman** [comment]
Done

**Comment by robertpeteuil** [comment]
Excellent.  A pull request has been submitted.
