### ISSUE TITLE
Testing appcast lists stable version

### ISSUE THREAD

**Issue by joshuajabbour** [gnachman/iterm2-website#40]
The testing appcast (https://iterm2.com/appcasts/testing.xml) includes the latest stable version, not the latest beta version (3.1.beta.5 at time of issue).

**Comment by gnachman** [comment]
The short answer is: it's complicated. Recent versions of iTerm2 will never request that URL without a query parameter which causes a redirect.

The long answer is: each user is randomly assigned a shard number from 0 to 99. Appcast URLs get the shard appended, like `https://iterm2.com/appcasts/testing.xml?shard=99`. New beta versions are gradually rolled out to more and more of the beta testers. Depending on your shard number, you'll get one of two beta versions. The newer beta is called the experimental version. During the early stages of 3.1 betas, which have just completed, most shards of the testing track pointed at 3.0.15 (in case there needed to be a 3.0.16), while a minority pointed at 3.1.beta.X. That has ended; now 100% of shards are in the experiment group. On the next beta of 3.1 I will make 3.1.x the control and set the experiment to 0%, and you will no longer see that the bare testing.xml will refer to 3.0.15.

**Comment by joshuajabbour** [comment]
Cool, thanks for the info. I had previously added the appcast to [the Homebrew cask](https://github.com/caskroom/homebrew-versions/pull/4045), but now I'm unsure if that is the right one to use. Seems like I did it right, as users explicitly asking for the latest beta should probably get it. But fyi...

**Comment by gnachman** [comment]
If you always want the latest, even if it has crazy bugs, use https://iterm2.com/appcasts/testing3.xml

That will always give you the experimental version of the beta.
