### ISSUE TITLE
Shell integration scripts generate an error on OpenBSD

### ISSUE THREAD

**Issue by kotfu** [gnachman/iterm2-website#41]
When sourcing the iterm2 shell integration script on OpenBSD, you get the following error:

        hostname: unknown option -- f
        usage: hostname [-s] [name-of-host]

On OpenBSD and NetBSD, there is no -f option for the hostname command. As a result the iterm2_hostname shell variable was always empty. You can work around this issue by setting the iterm2_hostname variable before you source the shell integration script.

**Comment by gnachman** [comment]
How are you supposed to get the fqdn on OpenBSD?

**Comment by kotfu** [comment]
I sent a pull request with the changes to fix this problem. On OpenBSD ```/etc/myname``` should contain the FQDN. At boot time, the contents of ```/etc/myname``` are use to set the host name. "$ hostname" with no options returns the FQDN. See [http://man.openbsd.org/myname.5](http://man.openbsd.org/myname.5) and [http://man.openbsd.org/hostname.1](http://man.openbsd.org/hostname.1) for all the details.
