### ISSUE TITLE
Unclear instructions on Utilities webpage

### ISSUE THREAD

**Issue by jkulesza** [gnachman/iterm2-website#44]
On https://www.iterm2.com/documentation-utilities.html, it states
> iTerm2 has a collection of shell scripts that help you take advantage of some of its unique features. **When you install Shell Integration, you're asked if you'd like to install the Utilities Package as well.**

This does not appear to be the case.  Instead, the process at https://www.iterm2.com/documentation-shell-integration.html (using either curl | bash, or curl and source) does not prompt the user to install the Utilities package.

**Comment by gnachman** [comment]
Fixed in 554633e

**Comment by jemus42** [comment]
I have tried this when SSH'd into a FreeBSD host, and while it managed to install the integration script (`.iterm2_shell_integration.zsh` in my case), it doesn't seem to download the utilities. There's no `~/.iterm2` and they're not in any other place I could think of.

I have both used the "Install shell integration" button in iTerm as well as downloading and manually sourcing the installation script.

Any hints? Not sure if this is a documentation issue or an iTerm2 issue. (Or a FreeBSD thing).

**Comment by gnachman** [comment]
This is the command that installs shell integration and utilities:
```
curl -L https://iterm2.com/shell_integration/install_shell_integration_and_utilities.sh | bash
```

**Comment by jemus42** [comment]
I am aware, and I tried that (on an unrelated note: FreeBSD doesn't ship with `bash` as far as I can tell)

As I said, `.iterm2_shell_integration.zsh` has been put in place successfully, but it was my understanding that there should also be a `~/.iterm2` folder with the utility scripts, which is not present.

**Comment by gnachman** [comment]
Sounds like the script is failing for some reason, and not having bash would only partially explain it since it should've failed completely rather than installing .iterm2_shell_integration.zsh.

If you can't install bash, the simplest thing will be to download the scripts from here:
https://github.com/gnachman/iterm2-website/tree/master/source/utilities
