### ISSUE TITLE
Add GPG signatures and hashes to download page

### ISSUE THREAD

**Issue by anarchistpenguin** [gnachman/iterm2-website#50]
For security purposes please add GPG signatures and sha256 hashes on the download page so users can check the integrity of the files.

Thank you.

**Comment by gnachman** [comment]
It is always at the bottom of the changelog. Click on "Show Changelog" and scroll down to see the SHA-256. Most people don't need to know it which is why it's at the bottom.

**Comment by anarchistpenguin** [comment]
Ah. Spotted it now. Thanks.
