### ISSUE TITLE
tcsh shell integration $loginsh

### ISSUE THREAD

**Issue by njalerikson** [gnachman/iterm2-website#70]
It seems misleading to rely on `$loginsh` to determine whether to run the shell integration script

https://github.com/gnachman/iterm2-website/blob/6acd1b77207148dc123103fc955c9c4a660157ba/source/misc/tcsh_startup.in#L7

since `$loginsh` is exclusively set when a shell is invoked as `tcsh -l`. Consequently, this results in the interactive sub-shells to not enable shell integration.

As such it would appear more appropriate to check for the `$prompt` which is set for all interactive shells - not just the login shell:

https://unix.stackexchange.com/a/26686

**Comment by gnachman** [comment]
Hm, this suggests that it also should be in .tcshrc and not .login. And for that matter, the bash shell integration script ought to use .bashrc (it already has a correct check for interactive shells).

The easiest solution is to update the installer. Some folks will wind up sourcing it twice, but the second one will have no effect.

I fixed the tcsh script in commit 02a1a889

**Comment by njalerikson** [comment]
Perfect!
