### ISSUE TITLE
All pages on iterm2.com 404

### ISSUE THREAD

**Issue by daxelrod** [gnachman/iterm2-website#73]
Currently, it appears that every page on https://iterm2.com returns

> Not Found
>
> The requested URL was not found on this server.
>
> Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

This doesn’t appear to be a problem with the code in this repo, but I wasn’t sure where else to report it.

Thank you for iTerm2, which is probably my most used application. Its ergonomics are fantastic.

**Comment by gnachman** [comment]
Fixed. uptimerobot.com was being abusive.
