### ISSUE TITLE
iTerm2 Zsh Shell Integration:  command line prompt started  with an unexcepted char?

### ISSUE THREAD

**Issue by newtorn** [gnachman/iterm2-website#74]
After I Installed Shell Integration,  iTerm2 command line prompt  started with  an unexcepted char, then I checked the .zshrc file, has shell command: `test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"`,  it alias iTerm2 shell integration tools, but before alias has some command that set prompt, then I do these operations.It works normally when do not execute `test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"`:
![isi](https://user-images.githubusercontent.com/43400069/70292613-9b7b0080-1819-11ea-9d8d-e66ebe4ec027.png)
Is this my problem, please tell me.

**Comment by gnachman** [comment]
The blue arrow is a mark, and it indicates that shell integration identified a shell prompt there. If you prefer not to see it, disable this setting:

![image](https://user-images.githubusercontent.com/427546/71055809-d596ad00-210b-11ea-8c98-9973deeb0530.png)
