### ISSUE TITLE
Remove Google Analytics

### ISSUE THREAD

**Issue by phenomax** [gnachman/iterm2-website#76]
Hi,

would you be willing to remove this Google Analytics 'functionality' from this website? There are better alternatives if you must keep tabs on users' activity.

Some reputable alternatives can be seen here: [switching.software/replace/google-analytics](https://switching.software/replace/google-analytics)

Disclaimer: Inspired by [a trending post in r/privacy](https://www.reddit.com/r/privacy/comments/gwsv5j/help_us_degoogle_foss_free_and_open_source/)

**Comment by gnachman** [comment]
Removed in 80dfbaf560ebd439bf0b3a82ed439b58b3b8bf3c. The website will be updated on the next push, hopefully this weekend when I publish 3.3.11.

**Comment by resynth1943** [comment]
Thanks @phenomax!

**Comment by TheEvilSkeleton** [comment]
> Thanks @phenomax!

and @gnachman
