### ISSUE TITLE
appcast URLs somehow not updated for 3.4.5. 

### ISSUE THREAD

**Issue by AntonioMeireles** [gnachman/iterm2-website#82]
hi @gnachman 

despite c54df5f10d97f91ab6aa5333533745dcc6c22dc1 the appcast URLs were not updated. for context got it because it had broken https://github.com/Homebrew/homebrew-cask/pull/104019. 

Thanks in advance and keep the great work! 

António

**Comment by gnachman** [comment]
I'm rolling it out slowly, which means the appcast will switch between 3.4.4 and 3.4.5 periodically this week. This is to limit the impact of serious bugs. Is there a better way to do this that won't break homebrew? Should I have a separate appcast just for them?

**Comment by AntonioMeireles** [comment]
@gnachman, 

thanks for the reply. fwiw i tried to update the cask in homebrew as i got the notification for iTerm that a new (stable) version was available, and i tend to prefer to do the updates out-of-app via the pkg manager. regarding your quewstion i'm unsure what would be homebrew's policy regarding this. will update [original issue](https://github.com/Homebrew/homebrew-cask/pull/104019) in order to try to find out  [IMHO, i may make sense to have available a separate appcast just to be consumed by package managers, but that's just me 😄]


All the best, and a great weekend!

**Comment by vitorgalvao** [comment]
Homebrew Cask maintainer here.

> Should I have a separate appcast just for them?

Doesn’t have to be a Sparkle appcast, in truth (though that would be nice and preferable). As long as your download links remain consistent, even a hosted `.txt` with the version in it would work.

**Comment by AntonioMeireles** [comment]
@gnachman 

FWIW ended workaround the root issue with this [commit](https://github.com/AntonioMeireles/homebrew-cask/commit/37d39f7c0abcf62b65617d0f61eee6cfe4865dae)  by pointing the livecheck  straight to this repo, as it's the source of truth anyway. 

All the best. 

António

**Comment by gnachman** [comment]
The canonical link to the newest version is always https://iterm2.com/downloads/stable/latest
