### ISSUE TITLE
Unable to update (no new version detected)

### ISSUE THREAD

**Issue by nick-f** [gnachman/iterm2-website#91]
👋  I've been unable to update iTerm since version 3.4.12. 

This seems to be a website issue rather than an iTerm issue, as looking at https://iterm2.com/appcasts/final_modern.xml shows 3.4.12 is the latest version. It's happening across two different computers and different browsers (I've tried Brave and Firefox).

<img width="1024" alt="final-modern" src="https://user-images.githubusercontent.com/754567/146273121-a0dce3a1-7041-43cf-95bb-7d463955d2ff.png">

I've been able to manually update by redownloading the latest version from the website, but that now needs to happen every time.

<img width="372" alt="iterm-update" src="https://user-images.githubusercontent.com/754567/146273187-52a3bb9d-f51a-494e-829b-feb830790462.png">

It's definitely odd because the latest version of the website repo definitely shows 3.4.15. https://github.com/gnachman/iterm2-website/blob/8b19952d66345c5cd0dded4a364c656a2fcc167f/source/appcasts/final_modern.xml

Any ideas what might be happening here?

**Comment by gnachman** [comment]
.13 and .14 had bugs and were removed from auto-update. .15 is in the soak period now and will go on autoupdate in a week if nothing catches on fire.

**Comment by nick-f** [comment]
Ah right, the soak period was something I hadn't accounted for. Thanks for the quick response!
